version: '3'
services:
    ecommerce_server:
        build: ./server
        image: ecommerce_server_image
        ports: 
            - "3000:80"
        volumes:
            - ./server:/var/www/
    ecommerce_client:
        build: ./client
        image: ecommerce_client_image
        ports:
            - "1234:1234"
        volumes:
            - ./:/usr/src
            - ecommerce_client_node_modules:/usr/src/client/node_modules

volumes:
    ecommerce_client_node_modules: